# 作者：zcy
"""模拟房源数据源（M1 阶段用于跑通链路；M3 接入 MCP 真实数据源替换）。
说明：以下为演示数据，仅用于开发与测试，非真实房源。"""

MOCK_LISTINGS: list[dict] = [
    # 河西区
    {"id": "mock-001", "title": "河西·万科公寓 精装一居", "source": "mock", "url": "https://mock/mock-001",
     "district": "河西", "address": "河西区文化广场旁", "price": 4200, "area": 45, "room_type": "1室",
     "orientation": "朝南", "floor": "中/18", "facilities": ["近地铁", "精装", "家电齐全", "电梯"],
     "listing_date": "2026-09-18", "is_verified": True, "risk_flags": [], "description": "精装一居，近地铁，拎包入住。"},
    {"id": "mock-002", "title": "河西·老小区两居 便宜", "source": "mock", "url": "https://mock/mock-002",
     "district": "河西", "address": "河西区永安里", "price": 3500, "area": 62, "room_type": "2室",
     "orientation": "南北", "floor": "3/6", "facilities": ["有燃气", "整租"],
     "listing_date": "2026-09-10", "is_verified": False, "risk_flags": ["无电梯"], "description": "老小区两居，价格实惠，需爬楼。"},
    {"id": "mock-003", "title": "河西·公寓开间 超低价", "source": "mock", "url": "https://mock/mock-003",
     "district": "河西", "address": "河西区某商务楼", "price": 2500, "area": 30, "room_type": "1室",
     "orientation": "朝北", "floor": "低/12", "facilities": ["近地铁"], "listing_date": "2026-08-25",
     "is_verified": False, "risk_flags": ["商水商电", "朝北"], "description": "开间，价格低，商水商电。"},
    # 滨湖区
    {"id": "mock-004", "title": "滨湖·阳光花园 两居带车位", "source": "mock", "url": "https://mock/mock-004",
     "district": "滨湖", "address": "滨湖区湖滨路", "price": 5000, "area": 78, "room_type": "2室",
     "orientation": "朝南", "floor": "中/20", "facilities": ["近地铁", "电梯", "车位", "精装"],
     "listing_date": "2026-09-20", "is_verified": True, "risk_flags": [], "description": "两居朝南，带车位，社区新。"},
    {"id": "mock-005", "title": "滨湖·青年社区 合租单间", "source": "mock", "url": "https://mock/mock-005",
     "district": "滨湖", "address": "滨湖区创想路", "price": 1800, "area": 20, "room_type": "1室",
     "orientation": "朝南", "floor": "高/15", "facilities": ["近地铁", "青年社区"],
     "listing_date": "2026-09-15", "is_verified": True, "risk_flags": ["合租"], "description": "合租单间，带独卫，青年社区氛围好。"},
    {"id": "mock-006", "title": "滨湖·精装一居 近产业园", "source": "mock", "url": "https://mock/mock-006",
     "district": "滨湖", "address": "滨湖区产业园旁", "price": 4600, "area": 50, "room_type": "1室",
     "orientation": "朝南", "floor": "中/24", "facilities": ["近地铁", "精装", "电梯", "智能门锁"],
     "listing_date": "2026-09-22", "is_verified": True, "risk_flags": [], "description": "一居朝南，近产业园，通勤方便。"},
    # 梁溪区
    {"id": "mock-007", "title": "梁溪·市中心一居", "source": "mock", "url": "https://mock/mock-007",
     "district": "梁溪", "address": "梁溪区中山路", "price": 3900, "area": 48, "room_type": "1室",
     "orientation": "朝东", "floor": "中/22", "facilities": ["近地铁", "电梯", "精装"],
     "listing_date": "2026-09-16", "is_verified": True, "risk_flags": [], "description": "市中心一居，通勤购物便利。"},
    {"id": "mock-008", "title": "梁溪·老城厢两居 近学校", "source": "mock", "url": "https://mock/mock-008",
     "district": "梁溪", "address": "梁溪区清名桥", "price": 3000, "area": 55, "room_type": "2室",
     "orientation": "朝南", "floor": "2/7", "facilities": ["整租", "近地铁"],
     "listing_date": "2026-09-05", "is_verified": False, "risk_flags": ["无电梯"], "description": "两居近学校，性价比高。"},
    {"id": "mock-009", "title": "梁溪·公寓 loft 一居", "source": "mock", "url": "https://mock/mock-009",
     "district": "梁溪", "address": "梁溪区青年路", "price": 3300, "area": 52, "room_type": "1室",
     "orientation": "朝南", "floor": "高/16", "facilities": ["电梯", "精装", "loft"],
     "listing_date": "2026-09-12", "is_verified": True, "risk_flags": ["商水商电"], "description": "Loft 一居，层高好。"},
    # 锡山区
    {"id": "mock-010", "title": "锡山·地铁口一居", "source": "mock", "url": "https://mock/mock-010",
     "district": "锡山", "address": "锡山区地铁2号线口", "price": 2700, "area": 40, "room_type": "1室",
     "orientation": "朝南", "floor": "中/11", "facilities": ["近地铁", "电梯"],
     "listing_date": "2026-09-19", "is_verified": True, "risk_flags": [], "description": "地铁口一居，通勤友好。"},
    {"id": "mock-011", "title": "锡山·两居 朝南采光好", "source": "mock", "url": "https://mock/mock-011",
     "district": "锡山", "address": "锡山区映月湖", "price": 3600, "area": 70, "room_type": "2室",
     "orientation": "朝南", "floor": "中/18", "facilities": ["近地铁", "电梯", "精装"],
     "listing_date": "2026-09-21", "is_verified": True, "risk_flags": [], "description": "两居朝南，采光好。"},
    {"id": "mock-012", "title": "锡山·远郊大两居 很便宜", "source": "mock", "url": "https://mock/mock-012",
     "district": "锡山", "address": "锡山区远郊", "price": 2200, "area": 88, "room_type": "2室",
     "orientation": "南北", "floor": "3/6", "facilities": ["整租"],
     "listing_date": "2026-08-30", "is_verified": False, "risk_flags": ["无电梯", "离地铁远"], "description": "大两居便宜，但离地铁远。"},
    # 新吴区
    {"id": "mock-013", "title": "新吴·科技园一居", "source": "mock", "url": "https://mock/mock-013",
     "district": "新吴", "address": "新吴区软件园旁", "price": 3200, "area": 42, "room_type": "1室",
     "orientation": "朝南", "floor": "中/17", "facilities": ["近地铁", "电梯"],
     "listing_date": "2026-09-14", "is_verified": True, "risk_flags": [], "description": "一居近科技园，上班方便。"},
    {"id": "mock-014", "title": "新吴·三居家庭房", "source": "mock", "url": "https://mock/mock-014",
     "district": "新吴", "address": "新吴区坊前", "price": 5200, "area": 100, "room_type": "3室",
     "orientation": "朝南", "floor": "中/28", "facilities": ["电梯", "精装", "车位"],
     "listing_date": "2026-09-11", "is_verified": True, "risk_flags": [], "description": "三居朝南，家庭入住。"},
    {"id": "mock-015", "title": "新吴·低价单间 需谨慎", "source": "mock", "url": "https://mock/mock-015",
     "district": "新吴", "address": "新吴区某群租楼", "price": 1500, "area": 15, "room_type": "1室",
     "orientation": "朝北", "floor": "低/3", "facilities": [],
     "listing_date": "2026-08-20", "is_verified": False, "risk_flags": ["疑似群租", "朝北", "证照不全"],
     "description": "超低价单间，疑似群租，风险提示。"},
    # 惠山区
    {"id": "mock-016", "title": "惠山·一居近地铁", "source": "mock", "url": "https://mock/mock-016",
     "district": "惠山", "address": "惠山区堰桥", "price": 2800, "area": 45, "room_type": "1室",
     "orientation": "朝南", "floor": "中/20", "facilities": ["近地铁", "电梯"],
     "listing_date": "2026-09-17", "is_verified": True, "risk_flags": [], "description": "一居近地铁，配套成熟。"},
    {"id": "mock-017", "title": "惠山·两居 精装", "source": "mock", "url": "https://mock/mock-017",
     "district": "惠山", "address": "惠山区钱桥", "price": 3400, "area": 68, "room_type": "2室",
     "orientation": "朝南", "floor": "中/14", "facilities": ["精装", "电梯", "近地铁"],
     "listing_date": "2026-09-13", "is_verified": True, "risk_flags": [], "description": "两居精装，近地铁。"},
    {"id": "mock-018", "title": "惠山·低价一居 离地铁远", "source": "mock", "url": "https://mock/mock-018",
     "district": "惠山", "address": "惠山区洛社", "price": 1900, "area": 38, "room_type": "1室",
     "orientation": "朝南", "floor": "4/6", "facilities": ["整租"],
     "listing_date": "2026-08-28", "is_verified": False, "risk_flags": ["离地铁远", "无电梯"], "description": "一居便宜，离地铁较远。"},
]
