# 作者：zcy
"""add payload to viewings

Revision ID: 6c352c941647
Revises: 5549416eb51d
Create Date: 2026-09-23 03:11:49.064112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c352c941647'
down_revision: Union[str, Sequence[str], None] = '5549416eb51d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viewings', sa.Column('payload', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viewings', 'payload')
    # ### end Alembic commands ###
